[package]
name = "decl_macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
decl_model.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
syn = { workspace = true, features = ["parsing"] }
